In [1]:
import numpy as np

In [9]:
x = np.array([0,1,2,3,4,5,6,7,8])
# Creating an ND-array of the numbers 0-8

In [4]:
type(x)
# An ND-array belongs to the type 'numpy.ndarray'

numpy.ndarray

In [8]:
isinstance(x, np.ndarray)

True

In [10]:
x = x.reshape(3,3)
# Reshaping the array to a 3x3array

In [11]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
np.power(x,2)
# Raising each element of the array to the 2nd power

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [13]:
np.mean(x,axis = 1)
# Taking the mean of each column of the array

array([1., 4., 7.])

In [14]:
x ** np.array([0., 1., 2.])

array([[ 1.,  1.,  4.],
       [ 1.,  4., 25.],
       [ 1.,  7., 64.]])

In [15]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
x[:2,:3]

array([[0, 1, 2],
       [3, 4, 5]])

In [17]:
x[x%2==0] *= -1

In [18]:
x

array([[ 0,  1, -2],
       [ 3, -4,  5],
       [-6,  7, -8]])

In [20]:
# A 0D array
np.array(8)

# A 1D array with shape (3,)
np.array([4.5,6.7,8.9])

# A 2D array with shape (3,2)
np.array([[84,9],
        [24,29],
        [36,40]])

# A 3D array with shape (2,2,2)
np.array([[[0,1],
        [2,3]],
        
        [[4,5],
        [6,7]]])

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [21]:
x= np.array([[[0,1],
        [2,3]],
        
        [[4,5],
        [6,7]]])

In [24]:
x[0, :, :1]
#get sheet 0, both rows, first column

array([[0],
       [2]])

In [25]:
#arrays use 0 based indexing
y = np.array([1,2,3])

In [26]:
y[0]

1

In [27]:
y[1]

2

In [28]:
y[2]

3

In [29]:
y[3]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [30]:
grades = np.array([[84,92],
        [64,79],
        [96,100]])

In [31]:
grades.shape

(3, 2)

In [32]:
grades[1,0]

64

In [33]:
grades[0:3,1]

array([ 92,  79, 100])

In [34]:
grades[1:,1]

array([ 79, 100])

In [35]:
grades[:,:1]

array([[84],
       [64],
       [96]])

In [36]:
grades[:,-1]

array([ 92,  79, 100])

In [37]:
grades[0]

array([84, 92])

In [38]:
x= np.array([[[0,1],
        [2,3]],
        
        [[4,5],
        [6,7]]])

In [39]:
x[0,1,0]

2

In [40]:
x[:,0,0]

array([0, 4])

In [41]:
x[1]

array([[4, 5],
       [6, 7]])

In [42]:
#Cannot index 0D arrays (they're not that useful)

In [43]:
x= np.array([[1,2,3,4],
            [5,6,7,8],
            [9,10,11,12]])

In [44]:
x.reshape(3,2,2)
# Reshaping must not change the size of the array

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [45]:
x.transpose()

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [46]:
x= np.arange(36)

In [47]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [53]:
x = np.arange(36).reshape(3,2,6)

In [54]:
x.shape

(3, 2, 6)

In [57]:
x.size

36

In [58]:
x.dtype
# Each integer in the array is stored using 64 bits of memory

dtype('int64')

In [59]:
x.itemsize
# Each integer is represented by 8 bytes of memory

8

In [60]:
np.array([i**2 for i in range(5)])

array([ 0,  1,  4,  9, 16])

In [61]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [62]:
np.linspace(0,10,5)
# Evenly spaced points

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [63]:
np.random.normal(1,5,10)
# normal distribution with mean 1, stdev 5

array([-0.94791285, 10.04755198, -3.09829612,  1.81121845, -4.49081851,
        3.40608107, -5.39942101,  8.44447409,  5.83065006,  0.42093232])

In [64]:
np.array([[[0]*4]*3]*2)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [66]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])